name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22.2'

      - name: Get dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run tests
        run: |
          go test -cover -v ./...
